//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKJVHHI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTable
    {
        public int LogId { get; set; }
        public string XMLData { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangedOn { get; set; }
    }
}
