//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKJVHHI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeNew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeNew()
        {
            this.EmpAddresses = new HashSet<EmpAddress>();
        }
    
        public int EmployeeId { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> ParentEmployeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpAddress> EmpAddresses { get; set; }
    }
}
