//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKJVHHI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.MyNewTables = new HashSet<MyNewTable>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserNameNvarchar { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> MyTinyInt { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<double> Price1 { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> DateTime2Field { get; set; }
        public Nullable<System.TimeSpan> DOBTime { get; set; }
        public Nullable<System.Guid> uniqueidentifierClm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyNewTable> MyNewTables { get; set; }
    }
}
