//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKJVHHI_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMyResult
    {
        public int EmployeeId { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> ParentEmployeeId { get; set; }
        public string EmpAddress { get; set; }
    }
}
